In [10]:
from array import*
arr1 = array('i',[1,2,3,4,5])
arr1.insert(2,7)
print(arr1)

array('i', [1, 2, 7, 3, 4, 5])
array('i', [1, 2, 7, 3, 4, 5])


In [ ]:
#insertion array
#time complexity is o(n) because we have move all the array to the end
#o(n) for inserting elemnet in middle
#o(1) for inserting elememnt in the end
#o(n) for inserting elemnet in a filled array because we have to create a newone

In [12]:
#array traversal
def traversalArray(array):
    for i in array:                               #for looping o(n) linear
        print(i)                                   #o(1) for printing constant
traversalArray(arr1)        

1
2
7
3
4
5


In [1]:
#accessing array
#searching array
from array import*
arr1 = array('i',[1,2,3,4,5,6])
def searcharray(array,value):
    for i in array:                     #o(n) for for loop
        if i == value:                   #o(1)
            return array.index(value)        #o(1)
    return "the element not found"              #o(1)
print(searcharray(arr1, 3))

#sapce complexity o(1)

2


In [10]:
#deletion array
from array import*
arr1 = array('i',[1,2,3,4,5,6])           
arr1.remove(2)
print(arr1)
#time complexity o(n) for removing element from middle and start
#o(1) for removing from last
#space complexity o(1)

array('i', [1, 3, 4, 5, 6])


In [5]:
#array/list questions
#how to find a missing number in an integer array of 1 to 100?

my_list = [1,2,3,4,5,6,7,8,10]

def findMissing(list, n):
    sum1 = n*(n+1)/2
    sum2 = sum(list)
    print("sum =",sum1-sum2)
    
findMissing(my_list, 10)    

sum = 9.0


In [12]:
#pairs/two sums
#[1,2,3,4] and given number 4 output will [1,3] or it van return the indices
my_array = [1,2,3,2,3,4,5,6]
def twoPair(list1, target):
    for i in range(len(list1)):
        for j in range(i+1, len(list1)):
            if list1[i] == list1[j]:
                pass
            elif list1[i] + list1[j] == target:
                print(i, j)
                
twoPair(my_array, 6)                

0 6
1 5
3 5


In [31]:
#find a number in an array

import numpy as np

my_array = np.array([1,2,3,4,5,6,7,8,9])

def numArray(list1, target):
    for i in list1:
        if list1[i] != target:
            return "numer doewnt exist"
        if list1[i] == target:
            return i
print(numArray(my_array, 10))    

numer doewnt exist


In [24]:
#find maximu product of two numbers in array
import numpy as np

myarray = np.array([1,2,9,4,8,6,7])
def maxMulti(list1):
    max1 = 0
    for i in range(len(list1)):
        for j in range(i+1, len(list1)):
            if list1[i] * list1[j] > max1:
                max1 = list1[i] * list1[j]
                pairs = str(list1[i]) +","+ str(list1[j])
    print(pairs)
    print(max1)
maxMulti(myarray)                

9,8
72


In [30]:
#implement algorithm to find a array is unique which it does not contains repeated elements

myArray = [1,2,3,4,5,6,4,8]
def isUnique(list1):
    a = []
    for i in list1:
        if i in a:
            print(i)
            return False
        else:
            a.append(i)
    return True        
print(isUnique(myArray))            
        

4
False


In [36]:
#permutations
#compare if the two list contanis same letters or words
def permutationOf(list1, list2):
    if len(list1) != len(list2):
        return False
    list1.sort()
    list2.sort()
    if list1 == list2:
        return True
list1 = ['a','b','c']
list2 = ['b','a','c']
print(permutationOf(list1, list2))

True


In [37]:
import numpy as np
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
myArray = [2,7,11,15]
def TwoSum(num, target):
    for i in range(len(num)):
        for j in range(i+1, len(num)):
            if num[i] + num[j] == target:
                print(i,j)
TwoSum(myArray, 9) 

0 1
